services:
  studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studio
    restart: always
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - APP_URL=https://studio.leonardkabo.cloud
    volumes:
      # Persistance de la base de données et des fichiers envoyés
      
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      # On force Traefik à utiliser ce réseau pour la communication interne
      - "traefik.docker.network=traefik-network"
      # Configuration du domaine
      - "traefik.http.routers.studio.rule=Host(`studio.leonardkabo.cloud`)"
      - "traefik.http.routers.studio.entrypoints=websecure"
      # Correction : On utilise 'mytlschallenge' trouvé via le docker inspect
      - "traefik.http.routers.studio.tls.certresolver=mytlschallenge"
      # Port interne de ton application
      - "traefik.http.services.studio.loadbalancer.server.port=3000"

networks:
  traefik-network:
    external: true
